
SONGS_with_MV = {
    "2018-06-04" : ("秒針を噛む",                 "Byoushinwo Kamu",        "GJI4Gv7NbmE"),
    "2018-10-02" : ("脳裏上のクラッカー",         "Nouriueno Cracker",      "3iAXclHlTTg"),
    "2018-11-06" : ("ヒューマノイド",             "Humanoid",               "GAB26GgJ8V8"),
    "2019-02-04" : ("眩しいDNAだけ",              "Mabushii DNA Dake",      "VJy8qZ77bpE"),
    "2019-05-08" : ("正義",                       "Seigi",                  "7kUbX4DoZoc"),
    "2019-09-26" : ("蹴っ飛ばした毛布",           "Kettobashita Moufu",     "iyCRK5WfFOI"),
    "2019-10-08" : ("こんなこと騒動",             "Konnakoto Soudou",       "mlA-Z7zSLHU"),
    "2019-10-18" : ("ハゼ馳せる果てるまで",       "Haze Haseru Haterumade", "ElnxZtiBDvs"),
    "2019-10-29" : ("Dear Mr 「F」",              "Dear. Mr\"F\"",          "Qw-FSw7d2zE"),
    "2020-03-06" : ("サターン(Acoustic ver.)",    "Saturn"  ,               "ubrovjZUi64"),
    "2020-05-14" : ("お勉強しといてよ",           "Study Me",               "Atvsg_zogxo"),
    "2020-07-13" : ("MILABO",                     "MILABO",                 "I88PrE-KUPk"),
    "2020-07-23" : ("低血ボルト",                 "Fastening",              "COll6PdtI5w"),
    "2020-08-11" : ("Ham",                        "Ham",                    "ouLndhBRL4w"),
    "2020-12-01" : ("勘ぐれい",                   "Hunch Gray",             "ugpywe34_30"),
    "2020-12-17" : ("正しくなれない",             "Can't be right",         "258qUAI7rck"),
    "2021-01-20" : ("暗く黒く",                   "Darken",                 "dcOwj-QE_ZE"),
    "2021-02-10" : ("胸の煙",                     "One's Mind",             "wQPgM-9LatM"),
    "2021-03-30" : ("勘冴えて悔しいわ",           "Kan Saete Kuyashiiwa",   "4QePrv24TBU"),
    "2021-06-18" : ("あいつら全員同窓会",         "Inside Joke",            "ZUwaudw8ht0"),
    "2021-07-04" : ("ばかじゃないのに",           "Stay Foolish",           "YgmFIVOR1-I"),
    "2021-12-02" : ("猫リセット",                 "Neko Reset",             "Sfz5TpCRSiI"),
    "2022-02-16" : ("袖のキルト",                 "Quilt",                  "9PnCSI8ndws"),
    "2022-04-07" : ("ミラーチューン",             "Mirror Tune",            "BVvvUGP0MFw"),
    "2022-09-08" : ("消えてしまいそうです",       "Blush",                  "OxcnK1s2Fww"),
    "2022-09-15" : ("夏枯れ",                     "Summer Slack",           "Nmemc-b6cdU"),
    "2022-10-20" : ("残機",                       "Time Left",              "6OC92oxs4gA"),
    "2022-12-15" : ("綺羅キラー",                 "Kira Killer",            "e5LaKxJVeVI"),
    "2023-05-15" : ("不法侵入",                   "Intrusion",              "SAdkxVFyAyc"),
    "2023-06-04" : ("花一匁",                     "Hanaichi Monnme",        "H88kps8X4Mk"),
    "2023-08-20" : ("馴れ合いサーブ",             "Nareai Serve",           "bIW0n36TUSQ"),
    "2024-05-23" : ("嘘じゃない",                 "Truth in Lies",          "GfDXqY-V0EY"),
    "2024-06-06" : ("Blues in the Closet",        "Blues in the Closet",    "E8RMWLoAsa0"),
    "2024-08-29" : ("海馬成長痛",                 "Hippocampal Pain",       "PLG2Uexyi9s"),
    "2024-10-23" : ("クズリ念",                   "KUZURI",                 "ut889MZ9yNo"),
    "2024-12-05" : ("TAIDADA",                    "TAIDADA",                "IeyCdm9WwXM"),
    "2025-02-28" : ("シェードの埃は延長",         "SHADE",                  "zjEMFuj23B4"),
    "2025-04-18" : ("微熱魔",                     "Warmthaholic",           "plpVOHqh3lA"),
    "2025-05-22" : ("クリームで会いにいけますか", "CREAM",                  "JQ2913bVo30"),
    "2025-06-12" : ("形",                         "Pain Give Form",         "6eFajRiOrpY"),
}

SONGS_all = [
    ("秒針を噛む"                       ,    "GJI4Gv7NbmE"),
    ("脳裏上のクラッカー"               ,    "3iAXclHlTTg"),
    ("ヒューマノイド"                   ,    "GAB26GgJ8V8"),
    ("眩しいDNAだけ"                    ,    "VJy8qZ77bpE"),
    ("正義"                             ,    "7kUbX4DoZoc"),
    ("蹴っ飛ばした毛布"                 ,    "iyCRK5WfFOI"),
    ("こんなこと騒動"                   ,    "mlA-Z7zSLHU"),
    ("ハゼ馳せる果てるまで"             ,    "ElnxZtiBDvs"),
    ("Dear Mr 「F」"                    ,    "Qw-FSw7d2zE"),
    ("サターン(Acoustic ver.)"          ,    "ubrovjZUi64"),
    ("お勉強しといてよ"                 ,    "Atvsg_zogxo"),
    ("MILABO"                           ,    "I88PrE-KUPk"),
    ("低血ボルト"                       ,    "COll6PdtI5w"),
    ("Ham"                              ,    "ouLndhBRL4w"),
    ("勘ぐれい"                         ,    "ugpywe34_30"),
    ("正しくなれない"                   ,    "258qUAI7rck"),
    ("暗く黒く"                         ,    "dcOwj-QE_ZE"),
    ("胸の煙"                           ,    "wQPgM-9LatM"),
    ("勘冴えて悔しいわ"                 ,    "4QePrv24TBU"),
    ("あいつら全員同窓会"               ,    "ZUwaudw8ht0"),
    ("ばかじゃないのに"                 ,    "YgmFIVOR1-I"),
    ("猫リセット"                       ,    "Sfz5TpCRSiI"),
    ("袖のキルト"                       ,    "9PnCSI8ndws"),
    ("ミラーチューン"                   ,    "BVvvUGP0MFw"),
    ("消えてしまいそうです"             ,    "OxcnK1s2Fww"),
    ("夏枯れ"                           ,    "Nmemc-b6cdU"),
    ("残機"                             ,    "6OC92oxs4gA"),
    ("綺羅キラー"                       ,    "e5LaKxJVeVI"),
    ("不法侵入"                         ,    "SAdkxVFyAyc"),
    ("花一匁"                           ,    "H88kps8X4Mk"),
    ("馴れ合いサーブ"                   ,    "bIW0n36TUSQ"),
    ("嘘じゃない"                       ,    "GfDXqY-V0EY"),
    ("Blues in the Closet"              ,    "E8RMWLoAsa0"),
    ("海馬成長痛"                       ,    "PLG2Uexyi9s"),
    ("クズリ念"                         ,    "ut889MZ9yNo"),
    ("TAIDADA"                          ,    "IeyCdm9WwXM"),
    ("シェードの埃は延長"               ,    "zjEMFuj23B4"),
    ("微熱魔"                           ,    "plpVOHqh3lA"),
    ("クリームで会いにいけますか"       ,    "JQ2913bVo30"),
    ("形"                               ,    "6eFajRiOrpY"),
    ("雲丹と栗"                         ,    "OtF5VtmhjnQ"),
    ("君がいて水になる"                 ,    "8jZ8Plz_SSM"),
    ("またね幻"                         ,    "6PpOOKEGX-4"),
    ("マイノリティ脈絡"                 ,    "v43Ke1W7zb4"),
    ("彷徨い酔い温度"                   ,    "SPam1BBKUjQ"),
    ("居眠り遠征隊"                     ,    "n5xGJHErs_A"),
    ("グラスとラムレーズン"             ,    "8FH4cBJ1y-E"),
    ("優しくLAST SMILE"                 ,    "00GDulz0q8w"),
    ("JK BOMBER"                        ,    "g3N3czs2U9s"),
    ("マリンブルーの庭園"               ,    "CBJ8Fre_SRk"),
    ("はゔぁ"                            ,    "Ws4OaBFAa_s)"),
    ("機械油"                           ,    "_JdiIp92rYk"),
    ("ろんりねす"                       ,    "h5CpUsC3Xi8"),
    ("繰り返す収穫"                     ,    "AIB36neGqt4"),
    ("過眠"                             ,    "4tDBohUTYAk"),
    ("奥底に眠るルーツ"                 ,    "o7jp25p-ZWU"),
    ("Darken (Twin Piano Live Version)" ,    "dD1Wm_B-M0Y"),
    ("上辺の私自身なんだよ"             ,    "GiRlt2bbEjQ"),
]

SONGS_live = [
    ("お勉強しといてよ from CLEANING LABO"              ,    "_WQNWVZqw4Q"),
    ("機械油 from CLEANING LABO"                        ,    "i8feIrHIO2k"),
    ("正義 from やきやきヤンキーツア"                   ,    "toiX8Wio6fQ"),
    ("JK BOMBER from ZUTOMAYO FACTORY"                  ,    "dLyx1tb5eSE"),
    ("あいつら全員同窓会 from ZUTOMAYO FACTORY"         ,    "o2tonXY8lCY"),
    ("サターン (ろんりー) from ZUTOMAYO FACTORY"        ,    "FGGbV5o-btA"),
    ("残機 from ROAD GAME"                              ,    "GNFjhvFnnDY"),
    ("秒針を噛む from ROAD GAME"                        ,    "2Ux6BA8Jlr4"),
    ("綺羅キラー (feat. Mori Calliope) from ROAD GAME"  ,    "HZK_9uWAqeo"),
    ("マイノリティ脈絡 from 本格中華喫茶・愛のペガサス" ,    "tkUag9Hxv_w"),
    ("暗く黒く（強）from 本格中華喫茶・愛のペガサス"    ,    "Al_9DytnKnY"),
    ("お勉強しといてよ from FUJI ROCK FESTIVAL ’24"    ,    "OcUSB26yN9k"),
    ("形 from ACAね 弾き語り"                           ,    "OF23IOVrOII"),
    ("クズリ念(肯定) from 名巧は愚なるが如し"           ,    "vQDA4fUzNEk"),
    ("TAIDADA from 名巧は愚なるが如し"                  ,    "ihZLtVsXEHs"),
    ("眩しいDNAだけ(EXPO 2025 ver.)"                    ,    "HzYCzNKQ5BY"),
    ("Spotify Go Stream Live"                           ,    "gWX-RAwBctU"),
    ("ZUTOMAYO FACTORY 鷹は飢えても踊り忘れず"          ,    "Pudux9RKL9I"),
    ("ROAD GAME『テクノプア』~叢雲のつるぎ~"            ,    "AeeykFh0mRA"),
]